#!/usr/bin/env node
/**
 * Improvement Report Generator
 * Consolidates all analysis results into a comprehensive report
 */

const fs = require('fs');
const path = require('path');

class ReportGenerator {
    constructor() {
        this.reports = {
            analysis: path.join(process.cwd(), 'test-analysis.json'),
            autofix: path.join(process.cwd(), 'auto-fix-report.json'),
            performance: path.join(process.cwd(), 'performance-report.json'),
            coverage: path.join(process.cwd(), 'coverage-report.json')
        };
    }

    async generate() {
        console.log('?? Generating Improvement Report...');

        try {
            // Load all reports
            const data = this.loadAllReports();
            
            // Generate markdown report
            const markdown = this.generateMarkdown(data);
            
            // Save report
            fs.writeFileSync(
                path.join(process.cwd(), 'improvement-report.md'),
                markdown
            );

            console.log('? Report saved to improvement-report.md');
            
        } catch (error) {
            console.error('? Report generation failed:', error.message);
        }
    }

    loadAllReports() {
        const data = {};

        Object.keys(this.reports).forEach(key => {
            const reportPath = this.reports[key];
            if (fs.existsSync(reportPath)) {
                try {
                    data[key] = JSON.parse(fs.readFileSync(reportPath, 'utf8'));
                } catch (error) {
                    console.warn(`??  Could not load ${key} report`);
                }
            }
        });

        return data;
    }

    generateMarkdown(data) {
        let md = '# ?? Self-Improving Test Agent Report\n\n';
        md += `Generated: ${new Date().toISOString()}\n\n`;
        md += '---\n\n';

        // Executive Summary
        md += '## ?? Executive Summary\n\n';
        md += this.generateSummary(data);
        md += '\n\n';

        // Test Analysis
        if (data.analysis) {
            md += '## ?? Test Analysis\n\n';
            md += this.formatTestAnalysis(data.analysis);
            md += '\n\n';
        }

        // Auto-Fix Results
        if (data.autofix) {
            md += '## ?? Auto-Fix Results\n\n';
            md += this.formatAutoFix(data.autofix);
            md += '\n\n';
        }

        // Performance Analysis
        if (data.performance) {
            md += '## ? Performance Analysis\n\n';
            md += this.formatPerformance(data.performance);
            md += '\n\n';
        }

        // Coverage Analysis
        if (data.coverage) {
            md += '## ?? Coverage Analysis\n\n';
            md += this.formatCoverage(data.coverage);
            md += '\n\n';
        }

        // Action Items
        md += '## ?? Action Items\n\n';
        md += this.generateActionItems(data);
        md += '\n\n';

        // Footer
        md += '---\n';
        md += '*This report was automatically generated by the Self-Improving Test Agent*\n';

        return md;
    }

    generateSummary(data) {
        let summary = '';
        
        // Test status
        if (data.analysis) {
            const metrics = data.analysis.metrics;
            const passRate = metrics.totalTests > 0 
                ? ((metrics.passedTests / metrics.totalTests) * 100).toFixed(1)
                : 0;
            
            summary += `**Test Status:** ${metrics.passedTests}/${metrics.totalTests} passed (${passRate}%)\n\n`;
        }

        // Auto-fixes applied
        if (data.autofix) {
            const status = data.autofix.success ? '? Success' : '?? Partial';
            summary += `**Auto-Fix Status:** ${status} - ${data.autofix.fixes.length} fix(es) applied\n\n`;
        }

        // Performance
        if (data.performance) {
            const trend = data.performance.trends.performance;
            const emoji = trend === 'improving' ? '??' : trend === 'degrading' ? '??' : '??';
            summary += `**Performance Trend:** ${emoji} ${trend}\n\n`;
        }

        // Coverage
        if (data.coverage) {
            const coverage = data.coverage.coverage;
            summary += `**Coverage:** ${coverage.lines.pct.toFixed(1)}% lines, ${coverage.branches.pct.toFixed(1)}% branches\n\n`;
        }

        return summary;
    }

    formatTestAnalysis(analysis) {
        let md = '';

        // Metrics
        md += '### Metrics\n\n';
        md += `- Total Tests: ${analysis.metrics.totalTests}\n`;
        md += `- ? Passed: ${analysis.metrics.passedTests}\n`;
        md += `- ? Failed: ${analysis.metrics.failedTests}\n`;
        md += `- ??  Skipped: ${analysis.metrics.skippedTests}\n`;
        md += '\n';

        // Issues
        if (analysis.issues && analysis.issues.length > 0) {
            md += '### Issues Detected\n\n';
            analysis.issues.forEach(issue => {
                const emoji = issue.severity === 'high' ? '??' : issue.severity === 'medium' ? '??' : '??';
                md += `${emoji} **${issue.type}**: ${issue.category || issue.metric || 'general'}\n`;
            });
            md += '\n';
        }

        // Recommendations
        if (analysis.recommendations && analysis.recommendations.length > 0) {
            md += '### Recommendations\n\n';
            analysis.recommendations.forEach((rec, idx) => {
                md += `${idx + 1}. [${rec.priority.toUpperCase()}] ${rec.action}\n`;
            });
            md += '\n';
        }

        return md;
    }

    formatAutoFix(autofix) {
        let md = '';

        md += `**Status:** ${autofix.success ? '? All fixes successful' : '?? Some fixes pending'}\n\n`;

        if (autofix.fixes.length > 0) {
            md += '### Fixes Applied\n\n';
            autofix.fixes.forEach((fix, idx) => {
                md += `${idx + 1}. **${fix.type}**: ${fix.action}\n`;
            });
            md += '\n';
        } else {
            md += '*No fixes were necessary*\n\n';
        }

        return md;
    }

    formatPerformance(performance) {
        let md = '';

        // Metrics
        md += '### Performance Metrics\n\n';
        md += `- Total Duration: ${performance.metrics.testDuration}ms\n`;
        md += `- Average Test Time: ${performance.metrics.averageTestTime.toFixed(2)}ms\n`;
        md += `- Memory Usage: ${(performance.metrics.memoryUsage.heapUsed / 1024 / 1024).toFixed(2)}MB\n`;
        md += '\n';

        // Trend
        if (performance.trends.direction) {
            md += '### Trend\n\n';
            md += `Performance is **${performance.trends.performance}** (${performance.trends.change.toFixed(2)}% ${performance.trends.direction})\n\n`;
        }

        // Bottlenecks
        if (performance.bottlenecks && performance.bottlenecks.length > 0) {
            md += '### Bottlenecks\n\n';
            performance.bottlenecks.forEach(b => {
                md += `- **${b.type}**: ${b.message}\n`;
            });
            md += '\n';
        }

        // Suggestions
        if (performance.suggestions && performance.suggestions.length > 0) {
            md += '### Optimization Suggestions\n\n';
            performance.suggestions.forEach((sug, idx) => {
                md += `${idx + 1}. [${sug.priority.toUpperCase()}] **${sug.category}**\n`;
                md += `   - Action: ${sug.action}\n`;
                md += `   - Implementation: ${sug.implementation}\n`;
                md += `   - Expected Impact: ${sug.expectedImprovement}\n\n`;
            });
        }

        return md;
    }

    formatCoverage(coverage) {
        let md = '';

        // Overall metrics
        md += '### Coverage Metrics\n\n';
        const cov = coverage.coverage;
        md += `- Lines: ${cov.lines.pct.toFixed(2)}%\n`;
        md += `- Statements: ${cov.statements.pct.toFixed(2)}%\n`;
        md += `- Functions: ${cov.functions.pct.toFixed(2)}%\n`;
        md += `- Branches: ${cov.branches.pct.toFixed(2)}%\n`;
        md += '\n';

        // Issues
        if (coverage.issues && coverage.issues.length > 0) {
            md += '### Coverage Issues\n\n';
            coverage.issues.forEach(issue => {
                md += `- **${issue.metric}**: ${issue.current.toFixed(2)}% (target: ${issue.threshold}%)\n`;
            });
            md += '\n';
        }

        // Suggestions
        if (coverage.suggestions && coverage.suggestions.length > 0) {
            md += '### Improvement Suggestions\n\n';
            coverage.suggestions.slice(0, 3).forEach((sug, idx) => {
                md += `${idx + 1}. [${sug.priority.toUpperCase()}] ${sug.file}\n`;
                md += `   - Current: ${sug.currentCoverage.toFixed(2)}%\n`;
                md += `   - ${sug.recommendation}\n\n`;
            });
        }

        return md;
    }

    generateActionItems(data) {
        let md = '';
        const actions = [];

        // Collect high-priority actions from all reports
        if (data.analysis && data.analysis.recommendations) {
            data.analysis.recommendations
                .filter(r => r.priority === 'high')
                .forEach(r => actions.push({ source: 'Analysis', action: r.action }));
        }

        if (data.performance && data.performance.suggestions) {
            data.performance.suggestions
                .filter(s => s.priority === 'high')
                .forEach(s => actions.push({ source: 'Performance', action: s.action }));
        }

        if (data.coverage && data.coverage.suggestions) {
            data.coverage.suggestions
                .filter(s => s.priority === 'high')
                .forEach(s => actions.push({ source: 'Coverage', action: s.recommendation }));
        }

        if (actions.length > 0) {
            actions.forEach((item, idx) => {
                md += `${idx + 1}. **[${item.source}]** ${item.action}\n`;
            });
        } else {
            md += '*No high-priority action items at this time* ?\n';
        }

        return md;
    }
}

// Run generator
const generator = new ReportGenerator();
generator.generate().catch(error => {
    console.error('Fatal error:', error);
    process.exit(1);
});
